version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "🤖 Dependencies"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
